USE [MASTER]
GO
DROP DATABASE [BuenDoctorData]
GO
CREATE DATABASE [BuenDoctorData]
GO
USE [BuenDoctorData]
GO
-------------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [PATIENT](
    [PATIENT_ID] NVARCHAR(10) NOT NULL,
    [FIRST_NAME] NVARCHAR(50) NOT NULL,
    [SECOND_NAME] NVARCHAR(50) NULL,
	[FIRST_SURNAME] NVARCHAR(50) NOT NULL,
	[SECOND_SURNAME] NVARCHAR(50) NOT NULL,
    [PROFILE_PICTURE] IMAGE NULL,
    [BIRTHDAY] DATE NOT NULL,
	[EMAIL] NVARCHAR(50) NULL,
    [PHONE] NVARCHAR(14) NULL,
    [MOBILE] NVARCHAR(14) NULL,
    [DIRECTION] NVARCHAR(100) NOT NULL,
    [NEIGHBORHOOD] NVARCHAR(100) NOT NULL,
    [CITY] NVARCHAR(100) NOT NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [PATIENT_PK] PRIMARY KEY ([PATIENT_ID]),
    CONSTRAINT [PATIENT_EMAIL_UK] UNIQUE ([EMAIL]),
    CONSTRAINT [PATIENT_EMAIL_CK] CHECK([EMAIL] LIKE '%@%.%'),
    CONSTRAINT [PATIENT_PHONE_CK] CHECK([PHONE] LIKE '+%'),
    CONSTRAINT [PATIENT_MOBILE_CK] CHECK([MOBILE] LIKE '+%'),
    CONSTRAINT [PATIENT_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0) 
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [USER_TYPE](
	[USER_TYPE_ID] TINYINT NOT NULL,
	[DESCRIPTION] NVARCHAR(20) NOT NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [USER_TYPE_PK] PRIMARY KEY ([USER_TYPE_ID]),
    CONSTRAINT [USER_TYPE_DESCRIPTION_UK] UNIQUE ([DESCRIPTION]),
    CONSTRAINT [USER_TYPE_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0)
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [DATA_USER](
    [DATA_USER_ID] NVARCHAR(10) NOT NULL,
    [FIRST_NAME] NVARCHAR(50) NOT NULL,
    [SECOND_NAME] NVARCHAR(50) NULL,
	[FIRST_SURNAME] NVARCHAR(50) NOT NULL,
	[SECOND_SURNAME] NVARCHAR(50) NOT NULL,
	[PASSWORD_HASH] VARBINARY(128) NULL,
    [PASSWORD_SALT] VARBINARY(128) NULL,
	[EMAIL] NVARCHAR(50) NULL,
    [MOBILE] NVARCHAR(14) NOT NULL,
	[PROFILE_PICTURE] IMAGE NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    [USER_TYPE_ID] TINYINT NOT NULL,
    CONSTRAINT [DATA_USER_PK] PRIMARY KEY ([DATA_USER_ID]),
    CONSTRAINT [DATA_USER_FK--USER_TYPE] FOREIGN KEY ([USER_TYPE_ID]) REFERENCES [USER_TYPE](USER_TYPE_ID),
    CONSTRAINT [DATA_USER_EMAIL_UK] UNIQUE ([EMAIL]),
    CONSTRAINT [DATA_USER_EMAIL_CK] CHECK([EMAIL] LIKE '%@buendoctor.%'),
    CONSTRAINT [DATA_USER_MOBILE_UK] UNIQUE ([MOBILE]),
    CONSTRAINT [DATA_USER_MOBILE_CK] CHECK([MOBILE] LIKE '+%'),
    CONSTRAINT [DATA_USER_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0) 
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [APPOINTMENT_STATUS](
	[APPOINTMENT_STATUS_ID] TINYINT NOT NULL,
	[DESCRIPTION] NVARCHAR(20) NOT NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [APPOINTMENT_STATUS_PK] PRIMARY KEY ([APPOINTMENT_STATUS_ID]),
    CONSTRAINT [APPOINTMENT_STATUS_DESCRIPTION_UK] UNIQUE ([DESCRIPTION]),
    CONSTRAINT [APPOINTMENT_STATUS_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0)
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [APPOINTMENT](
    [APPOINTMENT_ID] NVARCHAR(10) NOT NULL,
    [PATIENT_ID] NVARCHAR(10) NOT NULL,
    [DATA_USER_ID] NVARCHAR(10) NOT NULL,
    [DATE] SMALLDATETIME,
	[APPOINTMENT_STATUS_ID] TINYINT NOT NULL,
    CONSTRAINT [APPOINTMENT_PK] PRIMARY KEY ([APPOINTMENT_ID]),
    CONSTRAINT [APPOINTMENT_FK--PATIENT] FOREIGN KEY ([PATIENT_ID]) REFERENCES [PATIENT]([PATIENT_ID]),
    CONSTRAINT [APPOINTMENT_FK--USER] FOREIGN KEY ([DATA_USER_ID]) REFERENCES [DATA_USER]([DATA_USER_ID]),
    CONSTRAINT [APPOINTMENT_FK--APPOINTMENT_STATUS] FOREIGN KEY ([APPOINTMENT_STATUS_ID]) REFERENCES [APPOINTMENT_STATUS]([APPOINTMENT_STATUS_ID]),
);
GO
SET ANSI_PADDING OFF
GO
