USE [MASTER]
GO
DROP DATABASE [BUEN_DOCTOR-DATA]
CREATE DATABASE [BUEN_DOCTOR-DATA]
GO
USE [BUEN_DOCTOR-DATA]
GO
-------------------------------------------------------------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [PATIENT](
    [PATIENT_ID] NVARCHAR(10) NOT NULL,
    [FIRST_NAME] NVARCHAR(50) NOT NULL,
    [SECOND_NAME] NVARCHAR(50) NULL,
	[FIRST_SURNAME] NVARCHAR(50) NOT NULL,
	[SECOND_SURNAME] NVARCHAR(50) NOT NULL,
    [PROFILE_PICTURE] IMAGE NULL,
    [BIRTHDAY] DATE NOT NULL,
	[EMAIL] NVARCHAR(50) NULL,
    [PHONE] NVARCHAR(14) NULL,
    [MOBILE] NVARCHAR(14) NULL,
    [DIRECTION] NVARCHAR(100) NOT NULL,
    [NEIGHBORHOOD] NVARCHAR(100) NOT NULL,
    [CITY] NVARCHAR(100) NOT NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [PATIENT_PK] PRIMARY KEY ([PATIENT_ID]),
    CONSTRAINT [PATIENT_EMAIL_UK] UNIQUE ([EMAIL]),
    CONSTRAINT [PATIENT_EMAIL_CK] CHECK([EMAIL] LIKE '%@%.%'),
    CONSTRAINT [PATIENT_PHONE_CK] CHECK([PHONE] LIKE '+%'),
    CONSTRAINT [PATIENT_MOBILE_CK] CHECK([MOBILE] LIKE '+%'),
    CONSTRAINT [PATIENT_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0) 
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [USER_TYPE](
	[USER_TYPE_ID] TINYINT NOT NULL,
	[DESCRIPTION] NVARCHAR(20) NOT NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [USER_TYPE_PK] PRIMARY KEY ([USER_TYPE_ID]),
    CONSTRAINT [USER_TYPE_DESCRIPTION_UK] UNIQUE ([DESCRIPTION]),
    CONSTRAINT [USER_TYPE_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0)
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [USER](
    [USER_ID] NVARCHAR(10) NOT NULL,
    [FIRST_NAME] NVARCHAR(50) NOT NULL,
    [SECOND_NAME] NVARCHAR(50) NULL,
	[FIRST_SURNAME] NVARCHAR(50) NOT NULL,
	[SECOND_SURNAME] NVARCHAR(50) NOT NULL,
	[PASSWORD_HASH] VARBINARY(128) NULL,
    [PASSWORD_SALT] VARBINARY(128) NULL,
	[EMAIL] NVARCHAR(50) NULL,
    [PHONE] NVARCHAR(14) NOT NULL,
	[PROFILE_PICTURE] IMAGE NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [USER_PK] PRIMARY KEY ([USER_ID]),
    CONSTRAINT [USER_EMAIL_UK] UNIQUE ([EMAIL]),
    CONSTRAINT [USER_EMAIL_CK] CHECK([EMAIL] LIKE '%@%.%'),
    CONSTRAINT [USER_PHONE_UK] UNIQUE ([PHONE]),
    CONSTRAINT [USER_PHONE_CK] CHECK([PHONE] LIKE '+%'),
    CONSTRAINT [USER_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0) 
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [R-USER-USER_TYPE](
	[USER_ID] NVARCHAR(10) NOT NULL,
	[USER_TYPE_ID] TINYINT NOT NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [R-USER-USER_TYPE_FK--USER] FOREIGN KEY ([USER_ID]) REFERENCES [USER]([USER_ID]),
    CONSTRAINT [R-USER-USER_TYPE_FK--USER_TYPE] FOREIGN KEY ([USER_TYPE_ID]) REFERENCES [USER_TYPE](USER_TYPE_ID),
    CONSTRAINT [R-USER-USER_TYPE_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0) 
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [APPOINTMENT_TYPE](
	[APPOINTMENT_TYPE_ID] TINYINT NOT NULL,
	[DESCRIPTION] NVARCHAR(20) NOT NULL,
    [STATUS] BIT DEFAULT 1 NOT NULL,
    CONSTRAINT [APPOINTMENT_TYPE_PK] PRIMARY KEY ([APPOINTMENT_TYPE_ID]),
    CONSTRAINT [APPOINTMENT_TYPE_DESCRIPTION_UK] UNIQUE ([DESCRIPTION]),
    CONSTRAINT [APPOINTMENT_TYPE_STATUS_CK] CHECK([STATUS] = 1 OR [STATUS] = 0)
);
GO
SET ANSI_PADDING OFF
GO
--------------------------------------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [APPOINTMENT](
    [APPOINTMENT_ID] NVARCHAR(10) NOT NULL,
    [PATIENT_ID] NVARCHAR(10) NOT NULL,
    [USER_ID] NVARCHAR(10) NOT NULL,
    [DATE] SMALLDATETIME,
	[APPOINTMENT_TYPE_ID] TINYINT NOT NULL,
    CONSTRAINT [APPOINTMENT_PK] PRIMARY KEY ([APPOINTMENT_ID]),
    CONSTRAINT [APPOINTMENT_FK--PATIENT] FOREIGN KEY ([USER_ID]) REFERENCES [USER]([USER_ID]),
    CONSTRAINT [APPOINTMENT_FK--USER] FOREIGN KEY ([USER_ID]) REFERENCES [USER]([USER_ID]),
    CONSTRAINT [APPOINTMENT_FK--APPOINTMENT_TYPE] FOREIGN KEY ([APPOINTMENT_TYPE_ID]) REFERENCES [APPOINTMENT_TYPE]([APPOINTMENT_TYPE_ID]),
);
GO
SET ANSI_PADDING OFF
GO