USE [BuenDoctorData]
GO
INSERT INTO [USER_TYPE] VALUES (1,'Administrador',1);
INSERT INTO [USER_TYPE] VALUES (2,'médicos',1);
INSERT INTO [USER_TYPE] VALUES (3,'enfermeros',1);
INSERT INTO [USER_TYPE] VALUES (4,'fisioterapeutas',1);
GO

INSERT INTO [APPOINTMENT_TYPE] VALUES (1,'Atendido',1);
INSERT INTO [APPOINTMENT_TYPE] VALUES (2,'En servicio',1);
INSERT INTO [APPOINTMENT_TYPE] VALUES (3,'No atendido',1);
INSERT INTO [APPOINTMENT_TYPE] VALUES (4,'Asignado',1);
INSERT INTO [APPOINTMENT_TYPE] VALUES (5,'Anulada',1);
GO